version: '2'

services:

  mysql:
    image: dev-mysql:${MYSQL_VERSION}
    container_name: dev-mysql
    hostname: mysql
    stdin_open: true
    #tty: true
    ports:
      - "3306:3306"
    environment:
      TZ: "${TZ}"
      #MYSQL_USER: user
      #MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_CLIENT: '%.%.%.%'
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - "${MYSQL_DATA}:/var/lib/mysql"

  php-fpm:
    image: dev-php-fpm:${PHP_VERSION}
    build:
      context: .
      dockerfile: Dockerfile.php${PHP_VERSION}-fpm
    container_name: dev-php-fpm
    hostname: php-fpm
    ports:
      - "9000:9000"
    environment:
      TZ: "${TZ}"
    volumes:
      - "${WWW_DATA}:/var/www/html"
    links:
      - mysql
    depends_on:
      - mysql

  web:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: dev-nginx
    ports:
      - "80:80"
    environment:
      TZ: "${TZ}"
    volumes:
      - "${WWW_DATA}:/var/www/html"
      - "${NGINX_HOSTS_CONF}:/etc/nginx/conf.d"
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- "/home/alhaag/Projects/nginx-jwt:/etc/nginx/modules/nginx-jwt"
    links:
      - php-fpm
      - mysql
    depends_on:
      - php-fpm
